name: Skid Report
description: Report someone stealing our scripts or violating the license
title: "SKID: <skid github account name here>"
labels: ["skid"]
assignees:
  - Gradyruan
body:
  - type: input
    id: skid
    attributes:
      label: Skid
      description: Link to the skid
      placeholder: https://github.com/skidname/skid
    validations:
      required: true
  - type: textarea
    id: stolen
    attributes:
      label: Stolen
      description: What was stolen?
      placeholder: Stolen code
    validations:
      required: true
